app = "ai-privacy-app"
primary_region = "iad"

[build]

[env]
  PORT = "10000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1